import image1 from './img/d1.jpg';
import image3 from './img/d3.jpg';
import image4 from './img/d4.jpg';
import image5 from './img/d5.jpg';
import image6 from './img/d6.jpeg';


const data = [
    {
        id: 1,
        Drname: "Dr.Sanjay Fernandes",
        Education:"MD - Dermatology, DNB (Dermatology), DDV",
        cat:"Dermatologist",
        gender:"Male",
        PersonalInfo:"My favorite part of being a doctor is the opportunity to directly improve the health and wellbeing of my patients and to develop professional and personal relationships with them.",
        img:image1,
        fees:1000,
        experience:32,
        Languagesspoken:"English,Hindi",
        address:"Kurla West",
        city:"Mumbai",
        rating:21,
    },

    {
        id: 2,
        Drname:"Dr.Jeetendra Khatuja",
        Education:"MD - Dermatology, DNB (Dermatology), DDV",
        cat:"Trichologist",
        gender:"Male",
        PersonalInfo:"My favorite part of being a doctor is the opportunity to directly improve the health and wellbeing of my patients and to develop professional and personal relationships with them.",
        img: image3,
        fees:1000,
        experience:14,
        Languagesspoken:"English,Hindi",
        address:"Bandra West",
        city:"Mumbai",
        rating:357,
    },
    {
        id: 3,
        Drname:"Dr. Rameshwar Madhukar Rao Gutte - Dermatologist",
        Education:"FCPS (SKIN & VD), MD (Skin & VD), DDV (SKIN &VD), MBBS",
        cat:"General Physician",
        gender:"Male",
        PersonalInfo:"My favorite part of being a doctor is the opportunity to directly improve the health and wellbeing of my patients and to develop professional and personal relationships with them.",
        img:image3,
        fees:500,
        experience:18,
        Languagesspoken:"English,Hindi",
        address:"Kanjurmarg East",
        city:"Mumbai",
        rating:350,
    },
    {
        id: 4,
        Drname:"Dr. Ganesh Avhad - Dermatologist",
        Education:"MD, DNB, FIDP, FIL",
        cat:"Aesthetic Medicine Specialist",
        gender:"Male",
        PersonalInfo:"My favorite part of being a doctor is the opportunity to directly improve the health and wellbeing of my patients and to develop professional and personal relationships with them.",
        img: image4,
        fees:700,
        experience:12,
        Languagesspoken:"English,Hindi",
        address:"Sion East",
        city:"Mumbai",
        rating:21,
    },
    {
       

        id: 5,
        Drname:"Dr. Ruchi A. Gupta - Dermatologist",
        Education:"MD - Dermatology, MBBS",
        cat:"Yoga",
        gender:"Female",
        PersonalInfo:"My favorite part of being a doctor is the opportunity to directly improve the health and wellbeing of my patients and to develop professional and personal relationships with them.",
        img:image6,
        fees:1000,
        experience:22,
        Languagesspoken:"English,Hindi",
        address:"Kandivali East",
        city:"Mumbai",
        rating:121,
    },
    {
        id: 6,
        Drname:"Dr.Jeetendra Khatuja",
        Education:"MD - Dermatology, DNB (Dermatology), DDV",
        cat:"Unian Specialist",
        gender:"Male",
        PersonalInfo:"My favorite part of being a doctor is the opportunity to directly improve the health and wellbeing of my patients and to develop professional and personal relationships with them.",
        img: image4,
        fees:100,
        experience:2,
        Languagesspoken:"English,Hindi",
        address:"Vashi West",
        city:"Mumbai",
        rating:101,
    },
    {
        id: 7,
        Drname:"Dr.Jeetendra Khatuja",
        Education:"MD - Dermatology, DNB (Dermatology), DDV",
        cat:"Homeopathy Doctor",
        gender:"Male",
        PersonalInfo:"My favorite part of being a doctor is the opportunity to directly improve the health and wellbeing of my patients and to develop professional and personal relationships with them.",
        img:image5,
        fees:100,
        experience:22,
        Languagesspoken:"English,Hindi",
        address:"Belapure West",
        city:"Mumbai",
        rating:1,
    },
    {
        id: 8,
        Drname:"Dr.Jeetendra Khatuja",
        Education:"MD - Dermatology, DNB (Dermatology), DDV",
        cat:"Alternative Medicine Specialist",
        gender:"Male",
        PersonalInfo:"My favorite part of being a doctor is the opportunity to directly improve the health and wellbeing of my patients and to develop professional and personal relationships with them.",
        img: image4,
        fees:2000,
        experience:132,
        Languagesspoken:"English,Hindi",
        address:"Kurla West",
        city:"Mumbai",
        rating:201,
    },
]
export default data;